### ISSUE TITLE
[Big] auto load TemplateProfilerPanel

### ISSUE THREAD

**Issue by myusernamenone** [node13h/django-debug-toolbar-template-profiler#6]
Mode code line 58 - 65 to class TemplateProfilerPanel

https://github.com/node13h/django-debug-toolbar-template-profiler/blob/be03d58aa11cdbb2c7fd15d7ce574bc137c9a690/template_profiler_panel/panels/template.py#L58-L65

![capture](https://user-images.githubusercontent.com/32666202/32596547-bdd42b7c-c544-11e7-89ce-92274d233c60.PNG)

**Comment by adamchainz** [comment]
As I understand, you want the monkey patching done only if the panel is installed? That sounds very reasonable!
