### ISSUE TITLE
Use 'generate_stats' instead of 'process_response'

### ISSUE THREAD

**Issue by goffioul** [node13h/django-debug-toolbar-template-profiler#8]
This is required for django-debug-toolbar 2.

**Comment by blueyed** [comment]
..or rather `process_request`, no?

`generate_stats`'s doc says it might not be called on every request.

Ref: https://github.com/jazzband/django-debug-toolbar/commit/5299cf8 / https://github.com/jazzband/django-debug-toolbar/pull/1140

**Comment by Penagwin** [comment]
I was only able to get it to work by using `generate_stats`, I didn't have any luck with your pull request @blueyed
